version: '2'

services:
    
  react:
    container_name: react
    build:
      context: react_frontend
      dockerfile: Dockerfile
    volumes:
      - './react:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      app_subnet:
        ipv4_address: 10.10.1.6
networks:
  app_subnet:
    ipam:
      driver: default
      config:
        - subnet: 10.10.1.0/24
          gateway: 10.10.1.1

